Use fast path when we ask for just one key in Connect()
Expensify/react-native-onyx pull request #364
Opened 2023-09-23 13:12 UTC by Szymon20000

### Details

### Related Issues

GH_LINK

### Automated Tests

### Linked PRs

2023-09-25 13:57 UTC, mountiny requested changes

2023-09-25 13:57 UTC, mountiny commented on lib/Onyx.js
> +        })
I think it would be handy to leave a short comment about this.

2023-09-28 02:40 UTC, mountiny approved these changes
LGTM, thanks!

2023-09-28 02:42 UTC, merged

2023-10-19 18:27 UTC, marcaaron commented on lib/Onyx.js
> +                return [mapping.key];
NAB, but now that we do this - some of the comments below are a little misleading. Since this is not a key that we found (we just assumed it exists).