Migrate to `react-native-nitro-sqlite`
Expensify/react-native-onyx pull request #602
Opened 2024-11-26 17:10 UTC by chrispader

@mountiny 

### Details

This PR migrates Onyx to use `react-native-nitro-sqlite` instead of `react-native-quick-sqlite`.

There are only some minor changes to the types and usages of some operations, so there are no major logic changes.

Nitro now allows generic type parameters for `execute` and `executeAsync` and also includes general improvements to the API.

`react-native-nitro-sqlite` will need at least `react-natve@v0.74.0` as a peer dependency, but since we're already on `v0.75.2` in E/App, this shouldn't be a problem, right? 

### Related Issues

https://github.com/Expensify/App/issues/53063

### Automated Tests

### Manual Tests

### Author Checklist

- [ ] I linked the correct issue in the `### Related Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-11-26 17:19 UTC, mountiny reviewed
Can this be used with App that is not yet migrated the the nitro-sqlite?

2024-11-26 17:34 UTC, mountiny commented
@chrispader let @dominictb know when this si ready for testing and checklist

2024-11-26 17:43 UTC, mountiny commented
@chrispader does @dominictb need to use https://github.com/Expensify/App/pull/53149 with these changes?

2024-11-26 17:43 UTC, chrispader commented
> Can this be used with App that is not yet migrated the the nitro-sqlite?

@mountiny I've already migrated E/App too in https://github.com/Expensify/App/pull/53149. The changes could technically already be used, but i would hold on this PR to be merged first, so we can just bump the Onyx version in E/App instead of using a git commit.

2024-11-26 17:45 UTC, chrispader commented
> @chrispader does @dominictb need to use [Expensify/App#53149](https://github.com/Expensify/App/pull/53149) with these changes?

yes, i just added a note to `Manual Tests`

2024-12-03 10:05 UTC, chrispader commented
I'm pretty busy with other tasks this week, will look into this next monday

2024-12-11 12:00 UTC, chrispader commented on lib/storage/providers/SQLiteProvider.ts
> +                return undefined;
you're right, this should be null as well.

2024-12-11 16:26 UTC, chrispader commented
> Got this warning when I pressed `Pay with Expensify` for an expense report whose submitter does not have a bank account:
> 

I currently cannot reproduce this since i have no bank account/wallet set up.

This is a SQLite internal error, which should not be possible, since we never use transactions and rollbacks, but i'll have to look into this deeper once i have the bank account set up and i am able to click on "Pay with Expensify".

2024-12-17 15:47 UTC, chrispader commented
> Got this warning when I pressed `Pay with Expensify` for an expense report whose submitter does not have a bank account:

I cannot reproduce this. Do you have any specific repro steps for this? Does this warning appear right after you click the "Pay with Expensify" button?

https://github.com/user-attachments/assets/a1a377f9-1a9c-46ea-89d9-3db6f3de1799

2024-12-17 23:40 UTC, mountiny commented
@dominictb please let us know if you can still reproduce this

2024-12-26 13:33 UTC, chrispader commented
> Issue is no longer reproducible. But @chrispader Can you please help check [Expensify/App#53149 (comment)](https://github.com/Expensify/App/pull/53149#issuecomment-2558917185) to see if we can still proceed this PR?

@dominictb Since this is an issue in Swift itself, there won't be any fix in Nitro and therefore also not in NitroSQLite.

As Marc explained [in this comment](https://github.com/mrousavy/nitro/issues/422#issuecomment-2549056075), the problem only happens for iOS Simulator. I suggest either

- using Xcode 16.1 for now
- build for a physical device
- or bump the deployment target to `16.0` (but i'm not sure if we should and want to do this?)

2024-12-26 14:06 UTC, chrispader commented
> Issue is no longer reproducible. But @chrispader Can you please help check [Expensify/App#53149 (comment)](https://github.com/Expensify/App/pull/53149#issuecomment-2558917185) to see if we can still proceed this PR?

Addressed in https://github.com/Expensify/App/pull/53149#issuecomment-2562786065

2024-12-28 22:09 UTC, mountiny commented
Added hold for a fix in swift, @chrispader can you please link any discussions on how this can be tracked?

2024-12-29 09:19 UTC, chrispader commented
> Added hold for a fix in swift, @chrispader can you please link any discussions on how this can be tracked?

We can track progress on this in the [Nitro issue](https://github.com/mrousavy/nitro/issues/422), the [Swift issue](https://github.com/swiftlang/swift/pull/78242) and by checking whether the PR made it's way into recent releases.

As of now, it is not part of a new Swift release yet and i don't see any better way to track this unfortunately.

2025-04-15 12:17 UTC, chrispader commented
@dominictb @mountiny this is ready for review and the prerequisite for https://github.com/Expensify/App/pull/53149

2025-04-22 16:29 UTC, chrispader commented
> @chrispader Can you pull `main` please? Then we're good to go.

done! @dominictb

2025-04-22 22:06 UTC, mountiny submitted a review, later dismissed
Thanks! changes look good to me, tests should cover the main logic

2025-04-23 13:01 UTC, rlinoz approved these changes
Looks good to me!

2025-04-23 15:06 UTC, fabioh8010 requested changes
Changes are simple and look good to me! I have some questions though:

1. I know it's not the main goal of the issue, but I'm curious if we have any kind of performance improvements by using `react-native-nitro-sqlite` now? If yes, could you provide some info?
2. Do we need to think about a migration strategy here? Or everything is supposed to work same as before when using the new package? I'm more concerned about logged in users with stored data before/after this update.
3. Related to above, @chrispader I really appreciate if you add some manual tests around the App and provide videos for all platforms proving that this change is safe to ship 👍

2025-04-29 09:26 UTC, chrispader commented
> Changes are simple and look good to me! I have some questions though:
> 
> 1. I know it's not the main goal of the issue, but I'm curious if we have any kind of performance improvements by using `react-native-nitro-sqlite` now? If yes, could you provide some info?
> 2. Do we need to think about a migration strategy here? Or everything is supposed to work same as before when using the new package? I'm more concerned about logged in users with stored data before/after this update.
> 3. Related to above, @chrispader I really appreciate if you add some manual tests around the App and provide videos for all platforms proving that this change is safe to ship 👍

Thanks for the feedback!

1. There might be subtle performance improvements, but i don't think it will be too much of a difference. The main performance improvement comes from the optimizations in Nitro Modules around reducing boilerplate JSI calls and reducing complexity in general. The C++ implementation of NitroSQLite and SQLite in general were already very performant before.

There definitely shouldn't be worse performance than before, since our benchmarks indicated that NitroSQLite was always faster than the QuickSQLite due to performance gains from Nitro Modules.

2. Everything is supposed to work exactly as before. The API for e.g. `execute()` changed a bit compared to QuickSQLite, but the underlying persistence layer works exactly the same. In this PR, we handled all the necessary changes to Onyx to make it work like before. No user should be logged out and no should notice any change in the app.

3. Will add videos and tests in a bit. 🙌🏼


cc @dominictb

2025-05-02 13:17 UTC, rlinoz commented
@chrispader what are we missing here?

2025-05-02 13:20 UTC, chrispader commented
> @chrispader what are we missing here?

@rlinoz i don't think there's anything missing here, as long as testing and review are good

2025-05-04 07:57 UTC, chrispader commented
@rlinoz merge conflicts resolved, this should be ready to go!

2025-05-05 12:46 UTC, rlinoz commented on lib/storage/providers/SQLiteProvider.ts
> +enableSimpleNullHandling();
Hey @chrispader can you add the comment here?

2025-05-05 13:29 UTC, rlinoz approved these changes

2025-05-05 13:30 UTC, merged